name: Reusable OSV Vulnerability Scan

on:
  workflow_call:
    inputs:
      lockfile:
        required: true
        type: string

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OSV-Scanner
        run: osv-scanner --lockfile=${{ inputs.lockfile }}