name: OSV-Scanner PR Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read

jobs:
  setup-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, xml, zip, pdo_mysql

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          command: install --prefer-dist --no-progress --no-suggest

      - name: Update dependencies
        uses: php-actions/composer@v6
        with:
          command: update

  scan-pr:
    needs: setup-and-scan
    name: Run OSV Scanner
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v1.6.2-beta1