name: PHP CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, xml, zip, pdo_mysql

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run parallel linting
        run: composer test:lint

      - name: Run tests with PHPUnit
        run: composer test:phpunit

      - name: Run static analysis with PHPStan
        run: composer test:phpstan

      - name: Run static analysis with psalm
        run: composer test:psalm

      - name: Run rector for code quality
        run: composer test:rector

      - name: Fetch all tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Get latest tag
        id: latest-tag
        run: echo ::set-output name=tag::$(git tag | sort -V | tail -n1)

      - name: Increment the minor version
        id: new-tag
        run: |
          LATEST_TAG=${{ steps.latest-tag.outputs.tag }}
          MAJOR=$(echo $LATEST_TAG | cut -d. -f1)
          MINOR=$(echo $LATEST_TAG | cut -d. -f2)
          PATCH=$(echo $LATEST_TAG | cut -d. -f3)
          NEW_PATCH=$((PATCH+1))
          NEW_TAG="$MAJOR.$MINOR.$NEW_PATCH"
          echo ::set-output name=new_tag::$NEW_TAG

      - name: Create and push new tag
        if: github.ref == 'refs/heads/main'
        run: |
          NEW_TAG=${{ steps.new-tag.outputs.new_tag }}
          git tag $NEW_TAG
          git push origin $NEW_TAG
